/**
 * 100 Bear of the Month reason templates.
 * Commendation-style — all start with "For".
 * Only placeholder: {species} (used in ~30-40% of reasons).
 */
export const botmReasons: string[] = [
  // --- appearance / presentation ---
  "For outstanding shelf presence",
  "For fur that photographs exceptionally well",
  "For being a {species} in exactly the right condition",
  "For eyes that hold attention at a distance",
  "For being the most distinguished {species} on the table",
  "For an expression that requires no further explanation",
  "For a nose stitching of unusual precision",
  "For cleaning up better than any {species} had a right to",
  "For size that is exactly right",
  "For a coat in a shade not often seen on a {species} of this type",
  "For ears that are doing exactly what ears should do",
  "For posture that puts other {species} to shame",
  "For arriving in better condition than most",
  "For a ribbon that was already perfect on arrival",
  "For being a {species} whose patched ear only adds to the impression",
  "For looking considerably better after a Tuesday afternoon with a soft brush",
  "For being a {species} with the kind of face that makes people slow down",
  "For consistently looking ready",

  // --- stall behaviour / presence ---
  "For services to the front row",
  "For drawing people in without any assistance",
  "For being the most approachable {species} on the stall",
  "For making every neighbouring {species} look better by association",
  "For reliable performance across four consecutive events",
  "For consistent results on the middle shelf",
  "For being picked up by more visitors than any other {species} this month",
  "For attracting comment from people who were not planning to stop",
  "For services to the bottom shelf",
  "For being a {species} with steady and dependable shelf presence",
  "For making the table look like something is going on",
  "For being the {species} people show to whoever they came with",
  "For encouraging others nearby to also find homes",
  "For excellent visibility in low light conditions",

  // --- character / personality ---
  "For quiet dignity in all circumstances",
  "For patience that sets a standard others have not met",
  "For consistent cheerfulness across three events",
  "For a calm that is good to have at the front of the table",
  "For being a {species} with a settled sense of self",
  "For looking like the sort of {species} who keeps everyone else calm",
  "For resilience beyond what the job requires",
  "For being a {species} who maintained composure throughout the spring market season",
  "For an air of mild authority that is hard to explain",
  "For dignity in the face of repeated handling",
  "For being easy to be around",
  "For the kind of patience that earns recognition",
  "For a demeanour suited to any shelf in any home",
  "For looking as though nothing could rattle a {species} like them",
  "For character that does not require a label",

  // --- achievement / history ---
  "For surviving a car boot sale in November",
  "For services rendered at six separate events without complaint",
  "For being the {species} that made a box of mixed items worth stopping for",
  "For enduring a long wait and remaining entirely presentable",
  "For having clearly been somewhere and not letting it show",
  "For being a {species} who needed only minor repairs after what was evidently a full life",
  "For coming back from the back of the stall three times running",
  "For a restoration that came together in under an hour",
  "For surviving a village hall sale and still looking this good",
  "For new eyes fitted correctly on the first attempt",
  "For being the {species} I did not expect to find at that particular sale",
  "For joints that tightened up cleanly and held",
  "For a clean that made a genuine difference",
  "For having earned this more than once",
  "For arriving needing one thing and being entirely sorted after it",

  // --- dry / understated ---
  "For being a {species} that is impossible to put back down",
  "For making the decision easy this month",
  "For not requiring a lengthy deliberation",
  "For outstanding patience while sitting on the wrong shelf for three weeks",
  "For an expression that suggests prior experience of this kind of recognition",
  "For seeming entirely unbothered by the whole thing",
  "For keeping the standard high when the standard needed keeping",
  "For simply being a very good {species}",
  "For being the obvious choice, which is not as common as it sounds",
  "For making other selection criteria feel beside the point",
  "For being at the front of the stall in all senses",
  "For services to the stall that are easier to recognise than explain",
  "For being a {species} who was passed over twice and responded with continued excellence",
  "For being present at every event without ever making a fuss about it",
  "For the kind of quality that holds up under scrutiny",

  // --- warmth / finding a home ---
  "For being the sort of {species} someone has been looking for without knowing it",
  "For making it easy to imagine the right shelf",
  "For being a {species} that is good in the way that some things just are",
  "For being the {species} most likely to end up on a mantelpiece",
  "For the kind of appeal that is hard to walk away from",
  "For giving every indication of knowing exactly where they belong",
  "For deserving a home that appreciates the details",
  "For being exactly what this stall is for",
  "For being the {species} I keep coming back to when I think about who to choose",
  "For looking right in any light",
  "For being a {species} that is hard to forget once you have noticed them",
  "For being reliably good across every measure that matters",
  "For making the stall better just by being on it",

  // --- craft / restoration quality ---
  "For a repair that held across four events and shows no sign of going anywhere",
  "For being a {species} that proves good materials last",
  "For responding to careful work in exactly the way hoped",
  "For being the most satisfying restoration of the quarter",
  "For being a {species} where new stuffing made a genuine structural difference",
  "For being exactly what careful cleaning can do for the right {species}",
  "For demonstrating that a loose joint, once fixed, stays fixed",
  "For being the reason the soft brush gets regular use",
  "For coming back from the workbench looking like themselves",
  "For the kind of making that still holds after a long time",
];
